name: Update IPs

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点运行
  push:
    branches:
      - main

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update_ip.py
      run: python update_ip.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add IP
        git commit -m 'Update IP file'
        git push
